import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
const root = process.argv[2];
if (!root?.endsWith('/20260927T190500Z-chat-workspace-r2')) throw new Error('Unexpected release target');
const chat = path.join(root, 'chat-cloudflare');
const assets = path.join(chat, 'public/assets');
const mathNames = fs.readdirSync(assets).filter(n => /^katex-[a-f0-9]+\.mjs$/.test(n));
if (mathNames.length !== 1) throw new Error('Expected one existing deployed math bundle');
const math = fs.readFileSync(path.join(assets, mathNames[0]));
const digest = createHash('sha256').update(math).digest('hex').slice(0,16);
if (mathNames[0] !== `katex-${digest}.mjs`) throw new Error('Existing math bundle checksum mismatch');
const mathTarget = path.join(chat, 'node_modules/katex/dist/katex.mjs');
fs.mkdirSync(path.dirname(mathTarget), { recursive: true });
fs.writeFileSync(mathTarget, math);
for (const name of ['workspace-r2.js', 'workspace-r2.css']) fs.copyFileSync(path.join(assets, name), path.join(chat, 'frontend', name));
const buildPath = path.join(chat, 'scripts/build-frontend.mjs');
let build = fs.readFileSync(buildPath, 'utf8');
const old = '      [appName, app],';
if (build.split(old).length !== 2) throw new Error('Build anchor changed');
build = build.replace(old, '      ["workspace-r2.js", await readFile(join(FRONTEND_DIRECTORY, "workspace-r2.js"))],\n      ["workspace-r2.css", await readFile(join(FRONTEND_DIRECTORY, "workspace-r2.css"))],\n' + old);
fs.writeFileSync(buildPath, build);
console.log('EXISTING_MATH_BUNDLE_RESTORED', mathNames[0]);
console.log('WORKSPACE_ASSETS_INCLUDED_IN_BUILD');
